GET http://localhost:3000/products

###

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Description 1",
  "price": 100,
  "image_url": "http://localhost:9000/products/1.png"
}

###

GET http://localhost:3000/products/0517b3d0-c3f2-44e7-8aa3-995dabb09dad

###

PATCH  http://localhost:3000/products/0517b3d0-c3f2-44e7-8aa3-995dabb09dad
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Description 1"
}

###

DELETE http://localhost:3000/products/0517b3d0-c3f2-44e7-8aa3-995dabb09dad

###

GET http://localhost:3000/orders

###

POST http://localhost:3000/orders
Content-Type: application/json

{
  "items": [
    {
      "product_id": "04c4353a-3f6d-4272-a8f2-44b82c05ecc0",
      "quantity": 1
    },
    {
      "product_id": "04c4353a-3f6d-4272-a8f2-44b82c05ecc1",
      "quantity": 1
    }
  ],
  "cart_hash": "cart_hash_1"
}